<?php

// Include the features.
include_once('europeana_search.features.inc');

function europeana_search_perm() {
  return array(
    'configure europeana',
  );
}

function europeana_search_menu() {
  $items = array();

  $items['admin/settings/europeana'] = array(
    'title' => 'Search Europeana',
    'description' => t('Search the Europeana database'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('europeana_search_admin_form'),
    'access arguments' => array('configure europeana'),
  );
  
  return $items;  
}

function europeana_search_admin_form() {
  $form = array();
  
  $form['europeana_search_code'] = array(
    '#type' => 'textarea',
    '#title' => t('Widget code'),
    '#description' => t('Insert your generated code from http://www.europeana.eu/'),
    '#default_value' => variable_get('europeana_search_code', ''),
  );
  
  return system_settings_form($form);
}

/**
 * Implementation of hook_ctools_plugin_directory().
 *
 * Tells CTools (and thus Panels) where to look for plugin code.
 */
function europeana_search_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' || $module == 'panels') {
    return 'plugins/' . $plugin;
  }
}
